# Generated by Django 4.2.28 on 2026-06-19 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proc_tool', '0002_todo_completed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='completed',
        ),
        migrations.CreateModel(
            name='Step',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('completed', models.BooleanField(default=False)),
                ('order', models.IntegerField(default=0)),
                ('todo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='proc_tool.todo')),
            ],
        ),
    ]
